// Script to fetch Wikipedia images with better search term mapping
const fs = require('fs');

// Manual mappings for events that don't match Wikipedia titles
const manualMappings = {
  "Homer writes Iliad": "Homer",
  "Birth of Buddha": "Gautama_Buddha",
  "Birth of Confucius": "Confucius",
  "Plato founds Academy": "Plato",
  "Hannibal crosses Alps": "Hannibal",
  "Caesar conquers Gaul": "Gallic_Wars",
  "Constantine converts": "Constantine_the_Great",
  "Council of Nicaea": "First_Council_of_Nicaea",
  "Birth of Muhammad": "Muhammad",
  "Vikings raid Lindisfarne": "Lindisfarne",
  "Leif Erikson reaches America": "Leif_Erikson",
  "Crusaders take Jerusalem": "Siege_of_Jerusalem_(1099)",
  "Becket murdered": "Thomas_Becket",
  "Saladin takes Jerusalem": "Saladin",
  "Death of Genghis Khan": "Genghis_Khan",
  "Marco Polo reaches China": "Marco_Polo",
  "Mongol Empire peak": "Mongol_Empire",
  "William Wallace victory": "William_Wallace",
  "Chaucer's Canterbury Tales": "The_Canterbury_Tales",
  "Wars of Roses begin": "Wars_of_the_Roses",
  "Vasco da Gama reaches India": "Vasco_da_Gama",
  "Cortés conquers Aztecs": "Hernán_Cortés",
  "Magellan circumnavigation": "Ferdinand_Magellan",
  "Pizarro conquers Incas": "Francisco_Pizarro",
  "Copernicus heliocentric theory": "Nicolaus_Copernicus",
  "St. Bartholomew Massacre": "St._Bartholomew%27s_Day_massacre",
  "Jamestown founded": "Jamestown,_Virginia",
  "Galileo confirms heliocentrism": "Galileo_Galilei",
  "Charles I executed": "Charles_I_of_England",
  "Bach's Brandenburg Concertos": "Johann_Sebastian_Bach",
  "Mozart's Don Giovanni": "Don_Giovanni",
  "Marie Antoinette executed": "Marie_Antoinette",
  "Haiti independence": "Haitian_Revolution",
  "Napoleon invades Russia": "French_invasion_of_Russia",
  "British abolish slavery": "Slavery_Abolition_Act_1833",
  "Suez Canal opens": "Suez_Canal",
  "German Empire formed": "German_Empire",
  "Telephone patented": "Telephone",
  "Light bulb demonstrated": "Incandescent_light_bulb",
  "Wounded Knee": "Wounded_Knee_Massacre",
  "Modern Olympics begin": "1896_Summer_Olympics",
  "Victoria dies": "Queen_Victoria",
  "SF Earthquake": "1906_San_Francisco_earthquake",
  "Model T introduced": "Ford_Model_T",
  "US Women vote": "Nineteenth_Amendment_to_the_United_States_Constitution",
  "Tut's tomb found": "Tutankhamun",
  "Stalin takes power": "Joseph_Stalin",
  "Lindbergh flight": "Charles_Lindbergh",
  "Brown v. Board": "Brown_v._Board_of_Education",
  "Civil Rights Act": "Civil_Rights_Act_of_1964",
  "First email": "Email",
  "First PC": "Personal_computer",
  "AIDS recognized": "HIV/AIDS",
  "USSR dissolves": "Dissolution_of_the_Soviet_Union",
  "Mandela President": "Nelson_Mandela",
  "Dolly cloned": "Dolly_(sheep)",
  "Hong Kong returned": "Handover_of_Hong_Kong",
  "Diana dies": "Death_of_Diana,_Princess_of_Wales",
  "Y2K": "Year_2000_problem",
  "Euro circulation": "Euro",
  "Crimea annexed": "Annexation_of_Crimea_by_the_Russian_Federation",
  "Brexit vote": "Brexit",
  "First humans leave Africa": "Early_human_migrations",
  "Çatalhöyük settlement": "Çatalhöyük",
  "Domestication of horses": "Domestication_of_the_horse",
  "Writing invented in Sumer": "Cuneiform",
  "Stonehenge constructed": "Stonehenge",
  "First Egyptian dynasty": "First_Dynasty_of_Egypt",
  "Minoan civilization peak": "Minoan_civilization",
  "Iron Age begins": "Iron_Age",
  "Qin unifies China": "Qin_Shi_Huang",
  "Terracotta Army buried": "Terracotta_Army",
  "Silk Road opens": "Silk_Road",
  "Paper invented in China": "History_of_paper",
  "Khmer Empire peak": "Khmer_Empire",
  "Mongols conquer China": "Mongol_conquest_of_China",
  "Perry opens Japan": "Matthew_C._Perry",
  "Chinese Republic founded": "Republic_of_China_(1912–1949)",
  "Deng Xiaoping reforms": "Deng_Xiaoping",
  "Fukushima disaster": "Fukushima_nuclear_disaster",
  "Uruk becomes first city": "Uruk",
  "Sumerians invent writing": "Sumerian_language",
  "Cyrus conquers Babylon": "Cyrus_the_Great",
  "Maya civilization peak": "Maya_civilization",
  "Teotihuacan peak": "Teotihuacan",
  "Maya collapse": "Classic_Maya_collapse",
  "Inca Empire expands": "Inca_Empire",
  "Roanoke Colony vanishes": "Roanoke_Colony",
  "First enslaved Africans arrive": "Atlantic_slave_trade",
  "Pueblo Revolt": "Pueblo_Revolt",
  "Panama Canal opens": "Panama_Canal",
  "Phoenician alphabet spreads": "Phoenician_alphabet",
  "Palmyra flourishes": "Palmyra",
  "Sassanid Empire peak": "Sasanian_Empire",
  "House of Wisdom Baghdad": "House_of_Wisdom",
  "Seljuk Turks take Baghdad": "Seljuk_Empire",
  "Assassins fortress": "Order_of_Assassins",
  "Fall of Baghdad to Mongols": "Siege_of_Baghdad_(1258)",
  "Siege of Vienna fails": "Battle_of_Vienna",
  "Minoans decline": "Minoan_civilization",
  "Phoenicians found colonies": "Phoenicia",
  "Persian Wars end": "Greco-Persian_Wars",
  "Celtic La Tène culture": "La_Tène_culture",
  "Punic Wars begin": "Punic_Wars",
  "Caesar crosses Rubicon": "Crossing_the_Rubicon",
  "Diocletian divides empire": "Diocletian",
  "Visigoths sack Rome": "Sack_of_Rome_(410)",
  "Attila invades Europe": "Attila",
  "Lombards invade Italy": "Lombards",
  "Iconoclasm controversy": "Byzantine_Iconoclasm",
  "Alfred defeats Vikings": "Alfred_the_Great",
  "Italian Wars begin": "Italian_Wars",
  "European Coal and Steel": "European_Coal_and_Steel_Community",
  "Prague Spring crushed": "Prague_Spring",
  "Yugoslav Wars begin": "Yugoslav_Wars",
  "Good Friday Agreement": "Good_Friday_Agreement",
  "Euro introduced": "Euro",
  "Aristotle founds Lyceum": "Aristotle",
  "Euclid writes Elements": "Euclid",
  "Archimedes' discoveries": "Archimedes",
  "Dead Sea Scrolls written": "Dead_Sea_Scrolls",
  "Augustine writes Confessions": "Augustine_of_Hippo",
  "Boethius writes Consolation": "Boethius",
  "Aquinas writes Summa": "Thomas_Aquinas",
  "Petrarch crowned poet": "Petrarch",
  "Erasmus' Praise of Folly": "Erasmus",
  "Machiavelli's The Prince": "Niccolò_Machiavelli",
  "More's Utopia": "Thomas_More",
  "Montaigne invents essay": "Michel_de_Montaigne",
  "Bacon's Novum Organum": "Francis_Bacon",
  "Descartes' Meditations": "René_Descartes",
  "Pascal's Pensées": "Blaise_Pascal",
  "Locke's Essay on Understanding": "John_Locke",
  "Leibniz invents calculus": "Gottfried_Wilhelm_Leibniz",
  "Berkeley's idealism": "George_Berkeley",
  "Montesquieu's Spirit of Laws": "Montesquieu",
  "Diderot's Encyclopédie": "Encyclopédie",
  "Rousseau's Social Contract": "Jean-Jacques_Rousseau",
  "Bentham's utilitarianism": "Jeremy_Bentham",
  "Wollstonecraft's Vindication": "Mary_Wollstonecraft",
  "Schopenhauer's World as Will": "Arthur_Schopenhauer",
  "Mill's On Liberty": "John_Stuart_Mill",
  "Thoreau's Walden": "Henry_David_Thoreau",
  "Nietzsche's Zarathustra": "Friedrich_Nietzsche",
  "William James' Pragmatism": "William_James",
  "Wittgenstein's Tractatus": "Ludwig_Wittgenstein",
  "Heidegger's Being and Time": "Martin_Heidegger",
  "Gödel's incompleteness": "Kurt_Gödel",
  "Turing's computing paper": "Alan_Turing",
  "Sartre's Being and Nothingness": "Jean-Paul_Sartre",
  "Beauvoir's Second Sex": "Simone_de_Beauvoir",
  "Kuhn's Structure of Revolutions": "Thomas_Kuhn",
  "Rawls' Theory of Justice": "John_Rawls",
  "Foucault's Discipline and Punish": "Michel_Foucault",
  "Derrida's deconstruction": "Jacques_Derrida",
  "Aeschylus' Oresteia": "Aeschylus",
  "Sophocles' Oedipus Rex": "Sophocles",
  "Rumi's poetry": "Rumi",
  "Cervantes' Don Quixote": "Miguel_de_Cervantes",
  "Milton's Paradise Lost": "John_Milton",
  "Defoe's Robinson Crusoe": "Daniel_Defoe",
  "Richardson's Pamela": "Samuel_Richardson",
  "Fielding's Tom Jones": "Henry_Fielding",
  "Mary Shelley's Frankenstein": "Mary_Shelley",
  "Dickens' Oliver Twist": "Charles_Dickens",
  "Brontë's Jane Eyre": "Charlotte_Brontë",
  "Melville's Moby-Dick": "Herman_Melville",
  "Flaubert's Madame Bovary": "Gustave_Flaubert",
  "Dostoevsky's Crime and Punishment": "Fyodor_Dostoevsky",
  "Tolstoy's War and Peace": "Leo_Tolstoy",
  "Twain's Adventures of Tom Sawyer": "Mark_Twain",
  "Ibsen's A Doll's House": "Henrik_Ibsen",
  "Dostoevsky's Brothers Karamazov": "Fyodor_Dostoevsky",
  "Joyce's Ulysses": "James_Joyce",
  "Woolf's To the Lighthouse": "Virginia_Woolf",
  "Faulkner's Sound and Fury": "William_Faulkner",
  "Steinbeck's Grapes of Wrath": "John_Steinbeck",
  "Kerouac's On the Road": "Jack_Kerouac",
  "Achebe's Things Fall Apart": "Chinua_Achebe",
  "Lee's To Kill a Mockingbird": "Harper_Lee",
  "Solzhenitsyn's One Day": "Aleksandr_Solzhenitsyn",
  "García Márquez's 100 Years": "Gabriel_García_Márquez",
  "Morrison's Beloved": "Toni_Morrison",
  "Gregorian chant codified": "Gregorian_chant",
  "Guido invents notation": "Guido_of_Arezzo",
  "Notre-Dame school": "Notre-Dame_school",
  "Machaut's Messe de Nostre Dame": "Guillaume_de_Machaut",
  "Josquin's masses": "Josquin_des_Prez",
  "Monteverdi's Orfeo": "Claudio_Monteverdi",
  "Haydn's symphonies": "Joseph_Haydn",
  "Mozart's Marriage of Figaro": "The_Marriage_of_Figaro",
  "Schubert's Winterreise": "Franz_Schubert",
  "Chopin's études": "Frédéric_Chopin",
  "Wagner's Ring Cycle begins": "Richard_Wagner",
  "Brahms' First Symphony": "Johannes_Brahms",
  "Tchaikovsky's Swan Lake": "Pyotr_Ilyich_Tchaikovsky",
  "Debussy's Prélude": "Claude_Debussy",
  "Stravinsky's Rite of Spring": "Igor_Stravinsky",
  "Gershwin's Rhapsody in Blue": "George_Gershwin",
  "Robert Johnson records": "Robert_Johnson",
  "Messiaen's Quartet for End of Time": "Olivier_Messiaen",
  "Elvis on Ed Sullivan": "Elvis_Presley",
  "Beatles on Ed Sullivan": "The_Beatles",
  "Punk rock emerges": "Punk_rock",
  "Thriller released": "Michael_Jackson",
  "MTV launches": "MTV",
  "Hip-hop goes mainstream": "Hip_hop",
  "Egyptian pyramids art": "Egyptian_pyramids",
  "Greek sculpture golden age": "Ancient_Greek_sculpture",
  "Pompeii frescoes": "Pompeii",
  "Giotto's frescoes": "Giotto",
  "Van Eyck's Arnolfini Portrait": "Arnolfini_Portrait",
  "Botticelli's Birth of Venus": "The_Birth_of_Venus",
  "Leonardo's Last Supper": "The_Last_Supper_(Leonardo)",
  "Dürer's engravings": "Albrecht_Dürer",
  "Titian's Venus of Urbino": "Venus_of_Urbino",
  "Caravaggio's dramatic lighting": "Caravaggio",
  "Vermeer's Girl with Pearl Earring": "Girl_with_a_Pearl_Earring",
  "Rembrandt's Night Watch": "The_Night_Watch",
  "Goya's Third of May": "The_Third_of_May_1808",
  "Turner's seascapes": "J._M._W._Turner",
  "Courbet's Realism": "Gustave_Courbet",
  "Manet's Olympia": "Olympia_(Manet)",
  "Monet's Impression Sunrise": "Claude_Monet",
  "Van Gogh's Starry Night": "The_Starry_Night",
  "Munch's The Scream": "The_Scream",
  "Picasso's Les Demoiselles": "Les_Demoiselles_d%27Avignon",
  "Mondrian's geometric art": "Piet_Mondrian",
  "Dalí's Persistence of Memory": "The_Persistence_of_Memory",
  "Pollock's drip paintings": "Jackson_Pollock",
  "Rothko's color fields": "Mark_Rothko",
  "Warhol's Campbell's Soup": "Campbell%27s_Soup_Cans",
  "Basquiat emerges": "Jean-Michel_Basquiat",
  "Banksy's street art": "Banksy",
  "Hippocrates' medicine": "Hippocrates",
  "Chinese invent paper": "Paper",
  "Chinese invent gunpowder": "Gunpowder",
  "Chinese invent compass": "Compass",
  "Chinese invent printing": "Woodblock_printing",
  "Black Death arrives Europe": "Black_Death",
  "Brahe's observations": "Tycho_Brahe",
  "Harvey discovers circulation": "William_Harvey",
  "Hooke's Micrographia": "Robert_Hooke",
  "Halley predicts comet": "Edmond_Halley",
  "Linnaeus' taxonomy": "Carl_Linnaeus",
  "Galvani's electricity": "Luigi_Galvani",
  "Volta's battery": "Alessandro_Volta",
  "Dalton's atomic theory": "John_Dalton",
  "Faraday's electromagnetic induction": "Michael_Faraday",
  "Doppler effect discovered": "Doppler_effect",
  "Anesthesia first used": "Anesthesia",
  "Semmelweis handwashing": "Ignaz_Semmelweis",
  "Pasteur's germ theory": "Louis_Pasteur",
  "Mendel's genetics": "Gregor_Mendel",
  "Periodic table created": "Periodic_table",
  "Bell's telephone": "Alexander_Graham_Bell",
  "Edison's phonograph": "Thomas_Edison",
  "Koch identifies TB bacteria": "Robert_Koch",
  "Hertz discovers radio waves": "Heinrich_Hertz",
  "Marconi's radio": "Guglielmo_Marconi",
  "Curies discover radium": "Marie_Curie",
  "Planck's quantum theory": "Max_Planck",
  "Blood types discovered": "Blood_type",
  "Heavier-than-air flight": "Wright_brothers",
  "Einstein's relativity": "Albert_Einstein",
  "Model T mass production": "Ford_Model_T",
  "Rutherford's atomic nucleus": "Ernest_Rutherford",
  "Bohr's atomic model": "Niels_Bohr",
  "General relativity": "General_relativity",
  "Hubble's expanding universe": "Edwin_Hubble",
  "Antibiotics discovered": "Penicillin",
  "Splitting the atom": "Nuclear_fission",
  "Radar developed": "Radar",
  "First computer": "ENIAC",
  "Transistor invented": "Transistor",
  "Structure of DNA": "DNA",
  "Polio vaccine": "Polio_vaccine",
  "Sputnik orbits": "Sputnik_1",
  "Laser invented": "Laser",
  "First human in space": "Yuri_Gagarin",
  "Heart transplant": "Heart_transplantation",
  "ARPANET created": "ARPANET",
  "First test-tube baby": "In_vitro_fertilisation",
  "Smallpox eradicated": "Smallpox",
  "PC revolution": "Personal_computer",
  "HIV identified": "HIV",
  "Human Genome Project": "Human_Genome_Project",
  "Gravitational waves detected": "Gravitational_wave",
  "Hammurabi rules Babylon": "Hammurabi",
  "Hittite Empire peak": "Hittites",
  "Sea Peoples invasion": "Sea_Peoples",
  "Kingdom of Israel founded": "Kingdom_of_Israel_(united_monarchy)",
  "Assyrian Empire peak": "Neo-Assyrian_Empire",
  "Hanging Gardens built": "Hanging_Gardens_of_Babylon",
  "Cyrus frees Jews": "Cyrus_the_Great",
  "Greco-Persian Wars": "Greco-Persian_Wars",
  "Golden Age of Athens": "Classical_Athens",
  "Trial of Socrates": "Trial_of_Socrates",
  "Philip II unites Greece": "Philip_II_of_Macedon",
  "First Punic War": "First_Punic_War",
  "Second Punic War": "Second_Punic_War",
  "Spartacus slave revolt": "Spartacus",
  "Cleopatra rules Egypt": "Cleopatra",
  "Augustus becomes emperor": "Augustus",
  "Jesus crucified": "Crucifixion_of_Jesus",
  "Nero persecutes Christians": "Nero",
  "Jerusalem destroyed": "Siege_of_Jerusalem_(70_CE)",
  "Masada falls": "Siege_of_Masada",
  "Roman Empire peak": "Roman_Empire",
  "Edict of Milan": "Edict_of_Milan",
  "Roman Empire splits": "Fall_of_the_Western_Roman_Empire",
  "Sack of Rome": "Sack_of_Rome_(410)",
  "Western Rome falls": "Fall_of_the_Western_Roman_Empire",
  "Hagia Sophia built": "Hagia_Sophia",
  "Hegira to Medina": "Hegira",
  "Umar conquers Jerusalem": "Muslim_conquest_of_the_Levant",
  "Umayyad Caliphate peak": "Umayyad_Caliphate",
  "Viking Age begins": "Viking_Age",
  "Leif Erikson in America": "Leif_Erikson",
  "Great Schism": "East–West_Schism",
  "William conquers England": "Norman_Conquest",
  "First Crusade called": "First_Crusade",
  "Jerusalem captured": "Siege_of_Jerusalem_(1099)",
  "Angkor Wat built": "Angkor_Wat",
  "Saladin retakes Jerusalem": "Siege_of_Jerusalem_(1187)",
  "Fourth Crusade sacks Constantinople": "Fourth_Crusade",
  "Magna Carta": "Magna_Carta",
  "Marco Polo in China": "Marco_Polo",
  "Black Death begins": "Black_Death",
  "Hundred Years War resumes": "Hundred_Years%27_War",
  "Joan of Arc executed": "Joan_of_Arc",
  "Constantinople falls": "Fall_of_Constantinople",
  "Gutenberg prints Bible": "Gutenberg_Bible",
  "Columbus sails": "Christopher_Columbus",
  "Treaty of Tordesillas": "Treaty_of_Tordesillas",
  "Aztec Empire conquered": "Spanish_conquest_of_the_Aztec_Empire",
  "Reformation begins": "Reformation",
  "Magellan circumnavigates": "Ferdinand_Magellan",
  "Inca Empire conquered": "Spanish_conquest_of_the_Inca_Empire",
  "Akbar rules India": "Akbar",
  "Dutch independence declared": "Dutch_Republic",
  "Mayflower lands": "Mayflower",
  "Restoration": "Restoration_(England)",
  "Peter the Great reforms Russia": "Peter_the_Great",
  "Act of Union": "Acts_of_Union_1707",
  "American Revolution begins": "American_Revolutionary_War",
  "Constitution ratified": "United_States_Constitution",
  "Haitian independence": "Haitian_Revolution",
  "Waterloo": "Battle_of_Waterloo",
  "Latin American independence": "Spanish_American_wars_of_independence",
  "Opium War": "First_Opium_War",
  "Indian Rebellion": "Indian_Rebellion_of_1857",
  "Gettysburg": "Battle_of_Gettysburg",
  "German unification": "Unification_of_Germany",
  "Scramble for Africa": "Scramble_for_Africa",
  "Sino-Japanese War": "First_Sino-Japanese_War",
  "Russian Revolution of 1905": "Russian_Revolution_of_1905",
  "Chinese Revolution": "Xinhai_Revolution",
  "Armenian Genocide": "Armenian_genocide",
  "Easter Rising": "Easter_Rising",
  "WWI ends": "Armistice_of_11_November_1918",
  "Irish independence": "Irish_War_of_Independence",
  "USSR formed": "Soviet_Union",
  "Hitler takes power": "Adolf_Hitler",
  "Fall of France": "Fall_of_France",
  "Stalingrad": "Battle_of_Stalingrad",
  "Hiroshima": "Atomic_bombings_of_Hiroshima_and_Nagasaki",
  "Chinese Revolution": "Chinese_Communist_Revolution",
  "Stalin dies": "Joseph_Stalin",
  "Vietnam War begins": "Vietnam_War",
  "Hungarian uprising": "Hungarian_Revolution_of_1956",
  "Sputnik": "Sputnik_1",
  "Khmer Rouge": "Khmer_Rouge",
  "Soviet-Afghan War": "Soviet–Afghan_War",
  "Nelson Mandela freed": "Nelson_Mandela",
  "Gulf War": "Gulf_War",
  "Yugoslav Wars": "Yugoslav_Wars",
  "Afghanistan War": "War_in_Afghanistan_(2001–2021)",
  "Iraq War": "Iraq_War",
  "Global financial crisis": "Financial_crisis_of_2007–2008",
  "Syrian Civil War": "Syrian_civil_war",
  "COVID-19 pandemic": "COVID-19_pandemic",
  "Ukraine invaded": "Russian_invasion_of_Ukraine",
  "Rosetta Stone carved": "Rosetta_Stone",
  "Antikythera mechanism built": "Antikythera_mechanism",
  "Spartacus leads revolt": "Spartacus",
  "Cleopatra meets Caesar": "Cleopatra",
  "Battle of Alesia": "Battle_of_Alesia",
  "Paul's conversion": "Conversion_of_Paul_the_Apostle",
  "Boudica's rebellion": "Boudica",
  "Masada siege": "Siege_of_Masada",
  "Trajan's Column erected": "Trajan%27s_Column",
  "Severan dynasty begins": "Severan_dynasty",
  "Diocletian reforms Empire": "Diocletian",
  "Battle of Milvian Bridge": "Battle_of_the_Milvian_Bridge",
  "St. Jerome translates Bible": "Jerome",
  "Theodosius bans paganism": "Theodosius_I",
  "Vandals sack Rome": "Sack_of_Rome_(455)",
  "Clovis converts": "Clovis_I",
  "Benedict founds monastery": "Benedict_of_Nursia",
  "Plague of Justinian": "Plague_of_Justinian",
  "Battle of Badr": "Battle_of_Badr",
  "Arabs conquer Egypt": "Muslim_conquest_of_Egypt",
  "Uthman compiles Quran": "Uthman",
  "First fitna": "First_Fitna",
  "Venerable Bede's History": "Bede",
  "Donation of Pepin": "Donation_of_Pepin",
  "An Lushan Rebellion": "An_Lushan_Rebellion",
  "Viking raids intensify": "Viking_Age",
  "Cyrillic alphabet created": "Cyrillic_script",
  "Great Heathen Army": "Great_Heathen_Army",
  "Alfred the Great resists": "Alfred_the_Great",
  "Vladimir converts Russia": "Vladimir_the_Great",
  "Canute rules England": "Cnut",
  "Schism of 1054": "East–West_Schism",
  "Investiture Controversy": "Investiture_Controversy",
  "Crusaders massacre Jerusalem": "Siege_of_Jerusalem_(1099)",
  "Abelard and Heloise": "Peter_Abelard",
  "Second Crusade fails": "Second_Crusade",
  "Murder in Cathedral": "Thomas_Becket",
  "Third Crusade": "Third_Crusade",
  "Children's Crusade": "Children%27s_Crusade",
  "Francis founds Franciscans": "Francis_of_Assisi",
  "Mongol invasion begins": "Mongol_Empire",
  "Frederick II Crusade": "Frederick_II,_Holy_Roman_Emperor",
  "Kublai Khan rules China": "Kublai_Khan",
  "Swiss Confederation": "Old_Swiss_Confederacy",
  "Osman founds dynasty": "Osman_I",
  "Avignon Papacy": "Avignon_Papacy",
  "Battle of Bannockburn": "Battle_of_Bannockburn",
  "Great Famine": "Great_Famine_of_1315–1317",
  "Peasants' Revolt": "Peasants%27_Revolt",
  "Tamerlane conquers": "Timur",
  "Battle of Kosovo": "Battle_of_Kosovo",
  "Jan Hus burned": "Jan_Hus",
  "Vlad the Impaler rules": "Vlad_the_Impaler",
  "Lorenzo de' Medici rules Florence": "Lorenzo_de%27_Medici",
  "Ferdinand and Isabella marry": "Catholic_Monarchs",
  "Sistine Chapel begun": "Sistine_Chapel",
  "Richard III crowned": "Richard_III_of_England",
  "Bosworth Field": "Battle_of_Bosworth_Field",
  "Amerigo Vespucci explores": "Amerigo_Vespucci",
  "St. Peter's Basilica begun": "St._Peter%27s_Basilica",
  "Balboa sees Pacific": "Vasco_Núñez_de_Balboa",
  "Diet of Worms": "Diet_of_Worms",
  "Peasants' War": "German_Peasants%27_War",
  "Pizarro captures Atahualpa": "Francisco_Pizarro",
  "Calvin's Institutes": "John_Calvin",
  "Society of Jesus founded": "Society_of_Jesus",
  "Ivan the Terrible crowned": "Ivan_the_Terrible",
  "Book of Common Prayer": "Book_of_Common_Prayer",
  "Peace of Augsburg": "Peace_of_Augsburg",
  "Gregorian calendar adopted": "Gregorian_calendar",
  "Edict of Nantes": "Edict_of_Nantes",
  "East India Company founded": "East_India_Company",
  "Gunpowder Plot": "Gunpowder_Plot",
  "Galileo's telescope": "Galileo_Galilei",
  "First Thanksgiving": "Thanksgiving_(United_States)",
  "New Amsterdam founded": "New_Amsterdam",
  "Salem founded": "Salem,_Massachusetts",
  "Shimabara Rebellion": "Shimabara_Rebellion",
  "Japan closes borders": "Sakoku",
  "Witch trials peak": "Salem_witch_trials",
  "Anglo-Dutch Wars": "Anglo-Dutch_Wars",
  "Cromwell dies": "Oliver_Cromwell",
  "Great Plague of London": "Great_Plague_of_London",
  "Paradise Lost published": "Paradise_Lost",
  "Bill of Rights (English)": "Bill_of_Rights_1689",
  "Bank of England founded": "Bank_of_England",
  "Peter the Great's reforms": "Peter_the_Great",
  "First piano built": "Piano",
  "South Sea Bubble": "South_Sea_Company",
  "Voltaire in England": "Voltaire",
  "Wesley's conversion": "John_Wesley",
  "War of Austrian Succession": "War_of_the_Austrian_Succession",
  "Frederick the Great reigns": "Frederick_the_Great",
  "Jacobite Rising": "Jacobite_rising_of_1745",
  "Lisbon earthquake": "1755_Lisbon_earthquake",
  "Catherine the Great reigns": "Catherine_the_Great",
  "Stamp Act": "Stamp_Act_1765",
  "Boston Massacre": "Boston_Massacre",
  "First Continental Congress": "First_Continental_Congress",
  "Lexington and Concord": "Battles_of_Lexington_and_Concord",
  "Saratoga": "Battles_of_Saratoga",
  "Articles of Confederation": "Articles_of_Confederation",
  "Yorktown": "Siege_of_Yorktown",
  "Treaty of Paris": "Treaty_of_Paris_(1783)",
  "First Fleet arrives Australia": "First_Fleet",
  "Washington inaugurated": "George_Washington",
  "Bill of Rights ratified": "United_States_Bill_of_Rights",
  "Whitney's cotton gin": "Cotton_gin",
  "Directory established": "French_Directory",
  "Washington's Farewell": "George_Washington%27s_Farewell_Address",
  "Napoleon in Egypt": "French_campaign_in_Egypt_and_Syria",
  "Rosetta Stone found": "Rosetta_Stone",
  "Library of Congress founded": "Library_of_Congress",
  "Beethoven's Third Symphony": "Symphony_No._3_(Beethoven)",
  "Lewis and Clark expedition": "Lewis_and_Clark_Expedition",
  "Austerlitz": "Battle_of_Austerlitz",
  "Slave trade abolished (UK)": "Slave_Trade_Act_1807",
  "Peninsular War begins": "Peninsular_War",
  "Goethe's Faust Part I": "Johann_Wolfgang_von_Goethe",
  "War of 1812": "War_of_1812",
  "Napoleon exiled to Elba": "Napoleon",
  "Year Without Summer": "Year_Without_a_Summer",
  "Frankenstein published": "Frankenstein",
  "Prado Museum opens": "Museo_del_Prado",
  "Missouri Compromise": "Missouri_Compromise",
  "Greek War of Independence": "Greek_War_of_Independence",
  "Erie Canal opens": "Erie_Canal",
  "Audubon's Birds of America": "John_James_Audubon",
  "First passenger railroad": "Liverpool_and_Manchester_Railway",
  "Belgian independence": "Belgian_Revolution",
  "Nat Turner's rebellion": "Nat_Turner%27s_slave_rebellion",
  "Cholera pandemic": "1826–1837_cholera_pandemic",
  "Texas Revolution": "Texas_Revolution",
  "Penny post begins": "Penny_Black",
  "First telegraph message": "Electrical_telegraph",
  "Seneca Falls Convention": "Seneca_Falls_Convention",
  "Charge of Light Brigade": "Charge_of_the_Light_Brigade",
  "Bessemer steel process": "Bessemer_process",
  "John Brown's raid": "John_Brown%27s_raid_on_Harpers_Ferry",
  "Confederate states secede": "Confederate_States_of_America",
  "Gettysburg Address": "Gettysburg_Address",
  "Red Cross founded": "International_Red_Cross_and_Red_Crescent_Movement",
  "Lee surrenders": "Robert_E._Lee",
  "Thirteenth Amendment": "Thirteenth_Amendment_to_the_United_States_Constitution",
  "Canada Confederation": "Canadian_Confederation",
  "Transcontinental Railroad": "First_transcontinental_railroad",
  "Paris Commune": "Paris_Commune",
  "Yellowstone created": "Yellowstone_National_Park",
  "Impressionism exhibition": "Impressionism",
  "Zulu War": "Anglo-Zulu_War",
  "Tsar Alexander II killed": "Assassination_of_Alexander_II_of_Russia",
  "Chinese Exclusion Act": "Chinese_Exclusion_Act",
  "Berlin Conference": "Berlin_Conference",
  "Statue of Liberty dedicated": "Statue_of_Liberty",
  "Dreyfus Affair": "Dreyfus_affair",
  "Klondike Gold Rush": "Klondike_Gold_Rush",
  "Nobel Prizes first awarded": "Nobel_Prize",
  "Picasso's Demoiselles": "Les_Demoiselles_d%27Avignon",
  "NAACP founded": "NAACP",
  "Rite of Spring premieres": "The_Rite_of_Spring",
  "Battle of Verdun": "Battle_of_Verdun",
  "Somme offensive": "Battle_of_the_Somme",
  "Balfour Declaration": "Balfour_Declaration",
  "Armistice Day": "Armistice_of_11_November_1918",
  "Women's suffrage (US)": "Nineteenth_Amendment_to_the_United_States_Constitution",
  "Tutankhamun's tomb": "Tutankhamun",
  "Ulysses published": "Ulysses_(novel)",
  "Hitler's Beer Hall Putsch": "Beer_Hall_Putsch",
  "Lenin dies": "Vladimir_Lenin",
  "Scopes Trial": "Scopes_Trial",
  "General Strike (UK)": "1926_United_Kingdom_general_strike",
  "Lindbergh crosses Atlantic": "Charles_Lindbergh",
  "Stock market crash": "Wall_Street_Crash_of_1929",
  "Gandhi's Salt March": "Salt_March",
  "Empire State Building": "Empire_State_Building",
  "Japan invades Manchuria": "Japanese_invasion_of_Manchuria",
  "FDR elected": "Franklin_D._Roosevelt",
  "Reichstag Fire": "Reichstag_fire",
  "New Deal programs": "New_Deal",
  "Nuremberg Laws": "Nuremberg_Laws",
  "Italy invades Ethiopia": "Second_Italo-Ethiopian_War",
  "Guernica painting": "Guernica_(Picasso)",
  "Rape of Nanking": "Nanjing_Massacre",
  "Lend-Lease Act": "Lend-Lease",
  "Battle of Midway": "Battle_of_Midway",
  "Liberation of Paris": "Liberation_of_Paris",
  "Yalta Conference": "Yalta_Conference",
  "Dresden bombing": "Bombing_of_Dresden_in_World_War_II",
  "Hitler's death": "Death_of_Adolf_Hitler",
  "VE Day": "Victory_in_Europe_Day",
  "VJ Day": "Victory_over_Japan_Day",
  "Iron Curtain speech": "Iron_Curtain",
  "Indian partition": "Partition_of_India",
  "1984 published": "Nineteen_Eighty-Four",
  "Color TV introduced": "Color_television",
  "European Economic Community": "European_Economic_Community",
  "U-2 incident": "1960_U-2_incident",
  "Kennedy inaugurated": "John_F._Kennedy",
  "Bay of Pigs": "Bay_of_Pigs_Invasion",
  "Gagarin in space": "Yuri_Gagarin",
  "Silent Spring": "Silent_Spring",
  "Vietnam escalation": "Vietnam_War",
  "Tet Offensive": "Tet_Offensive",
  "RFK assassinated": "Assassination_of_Robert_F._Kennedy",
  "Kent State shootings": "Kent_State_shootings",
  "Bangladesh independence": "Bangladesh_Liberation_War",
  "Nixon visits China": "Richard_Nixon%27s_1972_visit_to_China",
  "Roe v. Wade": "Roe_v._Wade",
  "Oil crisis": "1973_oil_crisis",
  "Nixon resigns": "Resignation_of_Richard_Nixon",
  "Mao dies": "Mao_Zedong",
  "Camp David Accords": "Camp_David_Accords",
  "Iran hostage crisis": "Iran_hostage_crisis",
  "Reagan elected": "Ronald_Reagan",
  "AIDS epidemic": "HIV/AIDS",
  "Beirut bombing": "1983_Beirut_barracks_bombings",
  "Ethiopian famine": "1983–1985_famine_in_Ethiopia",
  "Gorbachev takes power": "Mikhail_Gorbachev",
  "Iran-Contra affair": "Iran–Contra_affair",
  "Intifada begins": "First_Intifada",
  "Velvet Revolution": "Velvet_Revolution",
  "German reunification": "German_reunification",
  "LA riots": "1992_Los_Angeles_riots",
  "Oslo Accords": "Oslo_Accords",
  "NAFTA begins": "North_American_Free_Trade_Agreement",
  "Dolly the sheep cloned": "Dolly_(sheep)",
  "Princess Diana dies": "Death_of_Diana,_Princess_of_Wales",
  "Columbine shooting": "Columbine_High_School_massacre",
  "Dot-com crash": "Dot-com_bubble",
  "Human genome mapped": "Human_Genome_Project",
  "Indian Ocean tsunami": "2004_Indian_Ocean_earthquake_and_tsunami",
  "Hurricane Katrina": "Hurricane_Katrina",
  "Haiti earthquake": "2010_Haiti_earthquake",
  "Higgs boson confirmed": "Higgs_boson",
  "Snowden revelations": "Edward_Snowden",
  "ISIS declared caliphate": "Islamic_State",
  "Paris attacks": "November_2015_Paris_attacks",
  "MeToo movement": "MeToo",
  "Parkland shooting": "Stoneman_Douglas_High_School_shooting",
  "George Floyd protests": "George_Floyd_protests",
  "Capitol riot": "2021_United_States_Capitol_attack",
  "Afghanistan withdrawal": "Withdrawal_of_United_States_troops_from_Afghanistan_(2020–2021)",
  "Queen Elizabeth II dies": "Death_and_state_funeral_of_Elizabeth_II",
  "Hammurabi's Code written": "Code_of_Hammurabi",
  "Phoenicians invent alphabet": "Phoenician_alphabet",
  "Zhou Dynasty begins": "Zhou_dynasty",
  "David becomes King of Israel": "David",
  "Solomon builds First Temple": "Solomon%27s_Temple",
  "Assyrian Empire conquers Israel": "Neo-Assyrian_Empire",
  "Thales predicts eclipse": "Thales_of_Miletus",
  "Cyrus issues decree": "Cyrus_the_Great",
  "Darius I builds Persepolis": "Persepolis",
  "Herodotus writes Histories": "Herodotus",
  "Thucydides writes history": "Thucydides",
  "Hippocrates practices medicine": "Hippocrates",
  "Socrates teaches philosophy": "Socrates",
  "Xenophon's Anabasis": "Xenophon",
  "Diogenes the Cynic": "Diogenes",
  "Zeno founds Stoicism": "Zeno_of_Citium",
  "Epicurus founds school": "Epicurus",
  "Ashoka converts to Buddhism": "Ashoka",
  "Burning of books in China": "Burning_of_books_and_burying_of_scholars",
  "Great Wall construction": "Great_Wall_of_China",
  "Cicero's orations": "Cicero",
  "Virgil writes Aeneid": "Virgil",
  "Livy writes history of Rome": "Livy",
  "Pliny's Natural History": "Pliny_the_Elder",
  "Plutarch's Lives": "Plutarch",
  "Hadrian builds wall": "Hadrian%27s_Wall",
  "Neo-Platonism founded": "Neoplatonism",
  "Mani preaches": "Mani_(prophet)",
  "Christian Bible compiled": "Biblical_canon",
  "Augustine converts": "Augustine_of_Hippo",
  "Patrick converts Ireland": "Saint_Patrick",
  "Columba founds Iona": "Columba",
  "Gregory the Great pope": "Pope_Gregory_I",
  "Isidore's Etymologies": "Isidore_of_Seville",
  "Bede completes history": "Bede",
  "Al-Khwarizmi's mathematics": "Muhammad_ibn_Musa_al-Khwarizmi",
  "Vikings discover Iceland": "Settlement_of_Iceland",
  "Al-Razi's medical texts": "Muhammad_ibn_Zakariya_al-Razi",
  "Averroes' commentaries": "Averroes",
  "Fibonacci's mathematics": "Fibonacci",
  "Francis receives stigmata": "Francis_of_Assisi",
  "Roger Bacon experiments": "Roger_Bacon",
  "Aquinas' Summa": "Summa_Theologica",
  "Dante finishes Comedy": "Dante_Alighieri",
  "William of Ockham": "William_of_Ockham",
  "Chaucer writes Tales": "Geoffrey_Chaucer",
  "Prince Henry's explorers": "Prince_Henry_the_Navigator",
  "Van Eyck's paintings": "Jan_van_Eyck",
  "First printed book": "Gutenberg_Bible",
  "Regiomontanus' astronomy": "Regiomontanus",
  "Ficino translates Plato": "Marsilio_Ficino",
  "Caxton prints in English": "William_Caxton",
  "Dias rounds Cape": "Bartolomeu_Dias",
  "Savonarola rules Florence": "Girolamo_Savonarola",
  "Aldine Press founded": "Aldine_Press",
  "Dürer's Apocalypse": "Albrecht_Dürer",
  "Erasmus' Adages": "Erasmus",
  "Bramante designs St. Peter's": "Donato_Bramante",
  "Utopia published": "Utopia_(book)",
  "Titian's masterpieces": "Titian",
  "Paracelsus reforms medicine": "Paracelsus",
  "Holbein paints Henry VIII": "Hans_Holbein_the_Younger",
  "Ignatius founds Jesuits": "Ignatius_of_Loyola",
  "Copernicus' Revolution": "Nicolaus_Copernicus",
  "Vasari's Lives": "Giorgio_Vasari",
  "Palestrina's masses": "Giovanni_Pierluigi_da_Palestrina",
  "Bruegel's paintings": "Pieter_Bruegel_the_Elder",
  "Mercator's projection": "Gerardus_Mercator",
  "Tycho's observations": "Tycho_Brahe",
  "El Greco paints Toledo": "El_Greco",
  "Giordano Bruno burned": "Giordano_Bruno",
  "Harvey's circulation": "William_Harvey",
  "Torricelli invents barometer": "Evangelista_Torricelli",
  "Westphalia peace": "Peace_of_Westphalia",
  "Vermeer's paintings": "Johannes_Vermeer",
  "Leibniz's calculus": "Gottfried_Wilhelm_Leibniz",
  "Locke's Essay": "John_Locke",
  "Couperin's harpsichord": "François_Couperin",
  "Watteau's paintings": "Antoine_Watteau",
  "Bach's Well-Tempered Clavier": "The_Well-Tempered_Clavier",
  "Vico's New Science": "Giambattista_Vico",
  "Hume's Treatise": "David_Hume",
  "Celsius temperature scale": "Anders_Celsius",
  "Montesquieu's Spirit": "Montesquieu",
  "Johnson's Dictionary": "Samuel_Johnson",
  "Mozart born": "Wolfgang_Amadeus_Mozart",
  "Beccaria on crimes": "Cesare_Beccaria",
  "Watt improves steam engine": "James_Watt",
  "Priestley discovers oxygen": "Joseph_Priestley",
  "Gibbon's Decline and Fall": "Edward_Gibbon",
  "Mesmer's magnetism": "Franz_Mesmer",
  "Mozart's Requiem": "Requiem_(Mozart)",
  "Eli Whitney's cotton gin": "Eli_Whitney",
  "Laplace's mechanics": "Pierre-Simon_Laplace",
  "Beethoven's Eroica": "Symphony_No._3_(Beethoven)",
  "Fulton's steamboat": "Robert_Fulton",
  "Brothers Grimm tales": "Brothers_Grimm",
  "Schubert's Lieder": "Franz_Schubert",
  "Champollion deciphers": "Jean-François_Champollion",
  "Beethoven's Ninth": "Symphony_No._9_(Beethoven)",
  "Niepce's photograph": "Nicéphore_Niépce",
  "Delacroix's Liberty": "Liberty_Leading_the_People",
  "Tocqueville's Democracy": "Alexis_de_Tocqueville",
  "Daguerre's photography": "Louis_Daguerre",
  "Poe's Raven": "Edgar_Allan_Poe",
  "Ether anesthesia": "Ether",
  "Monet's Impression": "Impression,_Sunrise",
  "Nietzsche's Zarathustra": "Thus_Spoke_Zarathustra",
  "Pasteur's rabies vaccine": "Louis_Pasteur",
  "Hertz proves radio waves": "Heinrich_Hertz",
  "Van Gogh's Starry Night": "The_Starry_Night",
  "Freud's psychoanalysis": "Sigmund_Freud",
  "Curie discovers radium": "Marie_Curie",
  "Picasso's Blue Period": "Pablo_Picasso",
  "Ford's assembly line": "Assembly_line",
  "Einstein's general relativity": "General_relativity",
  "Bauhaus founded": "Bauhaus",
  "Hubble's galaxies": "Edwin_Hubble",
  "Heisenberg uncertainty": "Uncertainty_principle",
  "Fleming discovers penicillin": "Alexander_Fleming",
  "Huxley's Brave New World": "Brave_New_World",
  "Sartre's existentialism": "Jean-Paul_Sartre",
  "ENIAC computer": "ENIAC",
  "Crick and Watson DNA": "Francis_Crick",
  "Polio vaccine success": "Jonas_Salk",
  "Chomsky's linguistics": "Noam_Chomsky",
  "Kuhn's paradigm shifts": "The_Structure_of_Scientific_Revolutions",
  "Quasars discovered": "Quasar",
  "Penzias finds cosmic background": "Arno_Allan_Penzias",
  "First heart transplant": "Christiaan_Barnard",
  "Email invented": "Email",
  "MRI developed": "Magnetic_resonance_imaging",
  "Personal computer age": "Personal_computer",
  "Walkman released": "Walkman",
  "Pac-Man released": "Pac-Man",
  "IBM PC launched": "IBM_Personal_Computer",
  "AIDS virus identified": "HIV",
  "DNA fingerprinting": "DNA_profiling",
  "Windows released": "Microsoft_Windows",
  "Voyager 2 at Neptune": "Voyager_2",
  "Hubble repairs": "Hubble_Space_Telescope",
  "Amazon founded": "Amazon_(company)",
  "Deep Blue beats Kasparov": "Deep_Blue_(chess_computer)",
  "Napster launched": "Napster",
  "SpaceX founded": "SpaceX",
  "Mars rovers land": "Mars_Exploration_Rover",
  "Pluto demoted": "Pluto",
  "Large Hadron Collider": "Large_Hadron_Collider",
  "iPad launched": "iPad",
  "Curiosity lands on Mars": "Curiosity_(rover)",
  "AlphaGo defeats Lee Sedol": "AlphaGo_versus_Lee_Sedol",
  "James Webb Telescope launches": "James_Webb_Space_Telescope",
  "First image of black hole": "Event_Horizon_Telescope"
};

// Read current index.html to extract all events
const html = fs.readFileSync('index.html', 'utf8');

// Extract all event names
const eventRegex = /\{e:"([^"]+)",y:/g;
const events = [];
let match;
while ((match = eventRegex.exec(html)) !== null) {
    events.push(match[1]);
}

console.log(`Found ${events.length} events`);

// Load existing images
let existingImages = {};
try {
    existingImages = JSON.parse(fs.readFileSync('event-images.json', 'utf8'));
    console.log(`Loaded ${Object.keys(existingImages).length} existing images`);
} catch(e) {
    console.log('No existing images file');
}

// Fetch image from Wikipedia
async function fetchWikiImage(searchTerm) {
    try {
        const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(searchTerm)}`);
        if (response.ok) {
            const data = await response.json();
            if (data.thumbnail && data.thumbnail.source) {
                return data.thumbnail.source;
            }
        }
    } catch(e) {}
    return null;
}

// Process all events
async function processEvents() {
    const images = { ...existingImages };
    let fetched = 0;
    let failed = 0;

    for (let i = 0; i < events.length; i++) {
        const event = events[i];

        // Skip if already have image
        if (images[event]) {
            continue;
        }

        // Try manual mapping first
        const mappedTerm = manualMappings[event];
        let image = null;

        if (mappedTerm) {
            image = await fetchWikiImage(mappedTerm);
        }

        if (image) {
            images[event] = image;
            fetched++;
            console.log(`[${i+1}/${events.length}] ✓ ${event}`);
        } else {
            failed++;
            console.log(`[${i+1}/${events.length}] ✗ ${event}`);
        }

        // Save progress every 50 events
        if ((fetched + failed) % 50 === 0) {
            fs.writeFileSync('event-images.json', JSON.stringify(images, null, 2));
            console.log(`Saved progress: ${Object.keys(images).length} images`);
        }

        // Rate limit
        await new Promise(r => setTimeout(r, 100));
    }

    // Final save
    fs.writeFileSync('event-images.json', JSON.stringify(images, null, 2));
    console.log(`\nDone! Total images: ${Object.keys(images).length}`);
    console.log(`Fetched: ${fetched}, Failed: ${failed}`);
}

processEvents();
